[package]
name = "lpr"
edition = "2024.alpha" # edition = "legacy" to use legacy (pre-2024) Move

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "devnet" }

[addresses]
lpr =  "0x0"
sui =  "0x2"
std =  "0x1"
